spring:
  application:
    name: Hospital-Management-System-Backend
  datasource:
    username: root
    password: Sahil@123
    url: jdbc:mysql://localhost:3306/HospitalDB?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true